template: moq
boilerplate-file: "./.boilerplate.txt"
mockname: "Moq{{.InterfaceName}}"
filename: "mocks_moq_test.go"
all: true
template-data:
    skip-ensure: False
    stub-impl: True
    with-resets: True
packages:
    github.com/vektra/mockery/v3/internal/fixtures:
        config:
            all: false
            include-regex: '.*'
            exclude-regex: 'RequesterGenerics'
        interfaces:
            Requester:
                configs:
                    - mockname: "Moq{{.InterfaceName}}SkipEnsure"
                      template-data:
                        skip-ensure: True
                    - {}
